import { createFeatureSelector } from '@ngrx/store';
import { createSlice } from '@reduxjs/toolkit';
import { PayloadAction } from '@reduxjs/toolkit/dist/createAction';
import { UserInfo } from '../models/UserInfo.model';
const initialState: UserInfo = {
  user_id: 0,
  aanmeld_datum: new Date(),
  datum: new Date(),
  account_code: '',
  username: '',
  wachtwoord: '',
  email: '',
  profielfoto: '',
  cover: '',
  views: 0,
  ip_aangemeld: '',
  ip_ingelogd: '',
  premiumaccount: 1,
  admin: 0,
  test: 0,
  spec: 0,
  Adminstatus: 0,
  wereld: '',
  silver: 75,
  gold: 300,
  bank: 0,
  storten: 5,
  store: null,
  profilestore: null,
  hasStore: 0,
  stelen: 0,
  races: 0,
  races_winst: 0,
  races_verlies: 0,
  werkervaring: 0,
  reclame: 0,
  reclameAanSinds: 0,
  online: '',
  voornaam: null,
  achternaam: null,
  geb_datum: '0000-00-00',
  land: '',
  character: '',
  profiel: '',
  youtube: null,
  teamzien: 1,
  buddieszien: 0,
  badgeszien: 0,
  muziekaan: 0,
  sneeuwaan: 0,
  dueluitnodiging: 1,
  buddy: '',
  blocklist: '',
  huis: '',
  geluksrad: 0,
  wiequiz: '',
  rank: 0,
  rankexp: 0,
  rankexpnodig: 0,
  soortwerk: 0,
  werktijd: 0,
  werktijdbegin: '0000-00-00 00:00:00',
  pokecentertijd: 0,
  pokecentertijdbegin: '0000-00-00 00:00:00',
  gevangenistijd: 0,
  gevangenistijdbegin: '0000-00-00 00:00:00',
  captcha_time: 0,
  captcha_tevaak_fout: 0,
  aantalpokemon: 0,
  badges: 0,
  pagina: '',
  gewonnen: 0,
  scramble: '0000-00-00 00:00:00',
  verloren: 0,
  eigekregen: 0,
  lvl_choose: '',
  pok_gezien: '',
  pok_bezit: '',
  pok_gehad: '',
  domass: 0,
  clan: '',
  missie_1: 0,
  missie_2: 0,
  missie_3: 0,
  missie_4: 0,
  missie_5: 0,
  missie_6: 0,
  missie_7: 0,
  missie_8: 0,
  missie_9: 0,
  missie_10: 0,
  nieuwsbrief: '',
  fish: 0,
  fishing: 0,
  legendkans: null,
  respect: 0,
  respect_add: 0,
  referer: '',
  hunt: null,
  promopoints_spent: 0,
  premium_lock: '0',
  ismobile: 0,
  battleScreen: 1,
  Abomasite: 0,
  Absolite: 0,
  Aerodactylite: 0,
  Aggronite: 0,
  Alakazite: 0,
  Altarianite: 0,
  Ampharosite: 0,
  Audinite: 0,
  Banettite: 0,
  Beedrillite: 0,
  Blastoisinite: 0,
  Blazikenite: 0,
  Cameruptite: 0,
  'Charizardite X': 0,
  'Charizardite Y': 0,
  Diancite: 0,
  Galladite: 0,
  Garchompite: 0,
  Gardevoirite: 0,
  Gengarite: 0,
  Glalitite: 0,
  Gyaradosite: 0,
  Heracronite: 0,
  Houndoominite: 0,
  Kangaskhanite: 0,
  Latiasite: 0,
  Latiosite: 0,
  Lopunnite: 0,
  Lucarionite: 0,
  Manectite: 0,
  Mawilite: 0,
  Medichamite: 0,
  Metagrossite: 0,
  'Mewtwonite X': 0,
  'Mewtwonite Y': 0,
  Pidgeotite: 0,
  Pinsirite: 0,
  Sablenite: 0,
  Salamencite: 0,
  Sceptilite: 0,
  Scizorite: 0,
  Sharpedonite: 0,
  Slowbronite: 0,
  Steelixite: 0,
  Swampertite: 0,
  Tyranitarite: 0,
  Venusaurite: 0,
  itembox: 'Bag',
  'Badge case': 0,
  'Poke ball': 0,
  'Great ball': 0,
  'Ultra ball': 0,
  'Premier ball': 0,
  'Net ball': 0,
  'Dive ball': 0,
  'Nest ball': 0,
  'Repeat ball': 0,
  'Timer ball': 0,
  'Master ball': 0,
  Potion: 0,
  'Super potion': 0,
  'Hyper potion': 0,
  'Full heal': 0,
  Revive: 0,
  'Max revive': 0,
  Pokedex: 0,
  'Pokedex chip': 0,
  'Pokedex zzchip': 0,
  'Fishing rod': 0,
  'Cave suit': 0,
  Bike: 1,
  Protein: 0,
  Iron: 0,
  Carbos: 0,
  Calcium: 0,
  'HP up': 0,
  'Rare candy': 0,
  Duskstone: 0,
  Firestone: 0,
  Leafstone: 0,
  Moonstone: 0,
  Ovalstone: 0,
  Shinystone: 0,
  Sunstone: 0,
  Thunderstone: 0,
  Waterstone: 0,
  Dawnstone: 0,
  Darkball: 0,
  items: 1,
};
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    updateUser: (state, action: PayloadAction<UserInfo>) => {
      return action.payload;
    },
  },
});
const {
  reducer,
  actions: { updateUser },
  name,
} = userSlice;
export default userSlice.reducer;
export { name, updateUser };
export const selectFeature =
  createFeatureSelector<ReturnType<typeof reducer>>(name);
