export interface UserInfo {
  user_id: number;
  aanmeld_datum: Date;
  datum: Date;
  account_code: string;
  username: string;
  wachtwoord: string;
  email: string;
  profielfoto: string;
  cover: string;
  views: number;
  ip_aangemeld: string;
  ip_ingelogd: string;
  premiumaccount: number;
  admin: number;
  test: number;
  spec: number;
  Adminstatus: number;
  wereld: string;
  silver: number;
  gold: number;
  bank: number;
  storten: number;
  store?: any;
  profilestore?: any;
  hasStore: number;
  stelen: number;
  races: number;
  races_winst: number;
  races_verlies: number;
  werkervaring: number;
  reclame: number;
  reclameAanSinds: number;
  online: string;
  voornaam?: any;
  achternaam?: any;
  geb_datum: string;
  land: string;
  character: string;
  profiel: string;
  youtube?: any;
  teamzien: number;
  buddieszien: number;
  badgeszien: number;
  muziekaan: number;
  sneeuwaan: number;
  dueluitnodiging: number;
  buddy: string;
  blocklist: string;
  huis: string;
  geluksrad: number;
  wiequiz: string;
  rank: number;
  rankexp: number;
  rankexpnodig: number;
  soortwerk: number;
  werktijd: number;
  werktijdbegin: string;
  pokecentertijd: number;
  pokecentertijdbegin: string;
  gevangenistijd: number;
  gevangenistijdbegin: string;
  captcha_time: number;
  captcha_tevaak_fout: number;
  aantalpokemon: number;
  badges: number;
  pagina: string;
  gewonnen: number;
  scramble: string;
  verloren: number;
  eigekregen: number;
  lvl_choose: string;
  pok_gezien: string;
  pok_bezit: string;
  pok_gehad: string;
  domass: number;
  clan: string;
  missie_1: number;
  missie_2: number;
  missie_3: number;
  missie_4: number;
  missie_5: number;
  missie_6: number;
  missie_7: number;
  missie_8: number;
  missie_9: number;
  missie_10: number;
  nieuwsbrief: string;
  fish: number;
  fishing: number;
  legendkans?: any;
  respect: number;
  respect_add: number;
  referer: string;
  hunt?: any;
  promopoints_spent: number;
  premium_lock: string;
  ismobile: number;
  battleScreen: number;
  Abomasite: number;
  Absolite: number;
  Aerodactylite: number;
  Aggronite: number;
  Alakazite: number;
  Altarianite: number;
  Ampharosite: number;
  Audinite: number;
  Banettite: number;
  Beedrillite: number;
  Blastoisinite: number;
  Blazikenite: number;
  Cameruptite: number;
  'Charizardite X': number;
  'Charizardite Y': number;
  Diancite: number;
  Galladite: number;
  Garchompite: number;
  Gardevoirite: number;
  Gengarite: number;
  Glalitite: number;
  Gyaradosite: number;
  Heracronite: number;
  Houndoominite: number;
  Kangaskhanite: number;
  Latiasite: number;
  Latiosite: number;
  Lopunnite: number;
  Lucarionite: number;
  Manectite: number;
  Mawilite: number;
  Medichamite: number;
  Metagrossite: number;
  'Mewtwonite X': number;
  'Mewtwonite Y': number;
  Pidgeotite: number;
  Pinsirite: number;
  Sablenite: number;
  Salamencite: number;
  Sceptilite: number;
  Scizorite: number;
  Sharpedonite: number;
  Slowbronite: number;
  Steelixite: number;
  Swampertite: number;
  Tyranitarite: number;
  Venusaurite: number;
  itembox: string;
  'Badge case': number;
  'Poke ball': number;
  'Great ball': number;
  'Ultra ball': number;
  'Premier ball': number;
  'Net ball': number;
  'Dive ball': number;
  'Nest ball': number;
  'Repeat ball': number;
  'Timer ball': number;
  'Master ball': number;
  Potion: number;
  'Super potion': number;
  'Hyper potion': number;
  'Full heal': number;
  Revive: number;
  'Max revive': number;
  Pokedex: number;
  'Pokedex chip': number;
  'Pokedex zzchip': number;
  'Fishing rod': number;
  'Cave suit': number;
  Bike: number;
  Protein: number;
  Iron: number;
  Carbos: number;
  Calcium: number;
  'HP up': number;
  'Rare candy': number;
  Duskstone: number;
  Firestone: number;
  Leafstone: number;
  Moonstone: number;
  Ovalstone: number;
  Shinystone: number;
  Sunstone: number;
  Thunderstone: number;
  Waterstone: number;
  Dawnstone: number;
  Darkball: number;
  items: number;
}
